
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern UNS8 Deviceinfo_Control;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS16 Deviceinfo_TP;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS16 Deviceinfo_RH;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS16 Deviceinfo_VL;		/* Mapped at index 0x2000, subindex 0x04 */
extern UNS16 Deviceinfo_CU;		/* Mapped at index 0x2000, subindex 0x05 */
extern UNS16 Deviceinfo_PW;		/* Mapped at index 0x2000, subindex 0x06 */
extern UNS16 Deviceinfo_VR;		/* Mapped at index 0x2000, subindex 0x07 */
extern UNS16 Deviceinfo_CPU;		/* Mapped at index 0x2000, subindex 0x08 */
extern UNS16 Deviceinfo_Res;		/* Mapped at index 0x2000, subindex 0x09 */
extern UNS8 Deviceinfo_SlaveAddress;		/* Mapped at index 0x2000, subindex 0x0A */

#endif // TESTSLAVE_H
